title: 好きgirl's Terminal
description: "Recursive Signal Vault | Enshin"
baseurl: "" # no subfolder
url: "https://sukigirl0101.github.io"
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
